from __future__ import annotations

import shutil
from pathlib import Path

from .capsule import Capsule


def export_pytest(capsule_path: str | Path, destination: str | Path) -> Path:
    source = Path(capsule_path).resolve()
    capsule = Capsule.load(source)
    tx_short = capsule.manifest.tx_id[2:10]
    target = Path(destination)
    target.parent.mkdir(parents=True, exist_ok=True)

    replay_dir = target.parent / "replays"
    replay_dir.mkdir(parents=True, exist_ok=True)
    replay_name = f"{tx_short}.genreplay"
    replay_path = replay_dir / replay_name
    shutil.copyfile(source, replay_path)

    code = f'''"""Generated by GenReplay from {capsule.manifest.tx_id}."""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from genreplay.capsule import Capsule
from genreplay.replay import ReplayEngine, scenario_from_capsule
from genreplay.rpc import GenLayerRpcClient

CAPSULE = Path(__file__).parent / "replays" / "{replay_name}"


def test_capsule_{tx_short}_integrity():
    capsule = Capsule.load(CAPSULE)
    assert capsule.verify_integrity()["ok"] is True


def test_capsule_{tx_short}_captured_identity():
    capsule = Capsule.load(CAPSULE)
    assert capsule.manifest.tx_id == "{capsule.manifest.tx_id}"


@pytest.mark.skipif(not os.getenv("GENREPLAY_RPC"), reason="set GENREPLAY_RPC for live validator replay")
def test_capsule_{tx_short}_validator_replay_has_no_rpc_error():
    capsule = Capsule.load(CAPSULE)
    scenario = scenario_from_capsule(capsule, round_number=0)
    rpc = GenLayerRpcClient(os.environ["GENREPLAY_RPC"])
    result = ReplayEngine(rpc).run(scenario)
    assert result.signature["status_code"] is not None
'''
    target.write_text(code, encoding="utf-8")
    return target
